# Generated by Django 6.1 on 2026-09-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0003_approval"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="metrics",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
