# Generated by Django 6.1 on 2026-09-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0004_message_metrics"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="cards",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
