# Generated by Django 6.1 on 2026-08-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_mcpintegration_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcpintegration',
            name='scopes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
