# Generated by Django 6.1 on 2026-08-24 06:30

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_mcpintegration_scopes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcpintegration',
            name='access_token',
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='mcpintegration',
            name='refresh_token',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
